apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "clusterkeep-ui.fullname" . }}-leaderboard
  labels:
    {{- include "clusterkeep-ui.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 64Mi
